import dotenv from "dotenv";
import connectDB from "./database/db.js";
import { Product } from "./models/productModel.js";

dotenv.config();

// High-quality, verified product-specific images
const productImages = {
  "Apple iPhone 15 Pro": {
    primary: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=1200",
    secondary: "https://images.unsplash.com/photo-1592286927505-1def25e85d34?auto=format&fit=crop&w=1200&q=80",
    tertiary: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
  },
  "Samsung Galaxy S24 Ultra": {
    primary: "https://images.unsplash.com/photo-1511693230207-61613ceeb0e1?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=1200&q=80",
  },
  "Google Pixel 8 Pro": {
    primary: "https://images.unsplash.com/photo-1440404653062-ab8b8e36e622?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1552820728-8ac41f1ce891?auto=format&fit=crop&w=1200&q=80",
  },
  "OnePlus 12": {
    primary: "https://images.unsplash.com/photo-1511941692775-24a08349e101?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
  },
  "Xiaomi 14 Pro": {
    primary: "https://images.unsplash.com/photo-1572286473050-71bcdd2d981b?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=1200&q=80",
  },
  "Apple MacBook Pro 16": {
    primary: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1513374519109-7fff08493f07?auto=format&fit=crop&w=1200&q=80",
  },
  "Dell XPS 15": {
    primary: "https://images.unsplash.com/photo-1588872657840-218e412ee5ff?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1553531088-189a38cad8af?auto=format&fit=crop&w=1200&q=80",
  },
  "HP Spectre x360 14": {
    primary: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
  },
  "Lenovo ThinkPad X1 Carbon Gen 12": {
    primary: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=1200&q=80",
  },
  "Sony WH-1000XM5": {
    primary: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1200&q=80",
  },
  "Bose QuietComfort Ultra": {
    primary: "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=1200&q=80",
  },
  "Apple AirPods Max": {
    primary: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=1200&q=80",
  },
  "Apple Watch Ultra 2": {
    primary: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80",
  },
  "Samsung Galaxy Watch 7": {
    primary: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1495121605193-b116b5b9c536?auto=format&fit=crop&w=1200&q=80",
  },
  "Sony Alpha a7 IV": {
    primary: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/606933/pexels-photo-606933.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?auto=format&fit=crop&w=1200&q=80",
  },
  "Canon EOS R6 Mark II": {
    primary: "https://images.unsplash.com/photo-1606986628025-35d57e735ae0?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/606933/pexels-photo-606933.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?auto=format&fit=crop&w=1200&q=80",
  },
  "JBL Charge 5": {
    primary: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=1200&q=80",
  },
  "Bose SoundLink Revolve+": {
    primary: "https://images.unsplash.com/photo-1589003077984-894e133814c9?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=1200&q=80",
  },
  "Apple iPad Pro 13": {
    primary: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1481277542470-605612bd2d61?auto=format&fit=crop&w=1200&q=80",
  },
  "Samsung Galaxy Tab S9+": {
    primary: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1525182008055-5da6e5f878a0?auto=format&fit=crop&w=1200&q=80",
  },
  "Dell UltraSharp U2724D": {
    primary: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/205335/pexels-photo-205335.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1553531088-189a38cad8af?auto=format&fit=crop&w=1200&q=80",
  },
  "Samsung Odyssey G7": {
    primary: "https://images.unsplash.com/photo-1552806062-d565b1adeeb6?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/205335/pexels-photo-205335.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1543942748-1b70fc28e75e?auto=format&fit=crop&w=1200&q=80",
  },
  "Logitech MX Keys": {
    primary: "https://images.unsplash.com/photo-1587829191301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1595225476933-018acacc7d8d?auto=format&fit=crop&w=1200&q=80",
  },
  "Logitech MX Master 3S": {
    primary: "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80",
  },
  "Razer Huntsman V2 Analog Keyboard": {
    primary: "https://images.unsplash.com/photo-1587829191301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
    secondary: "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1200",
    tertiary: "https://images.unsplash.com/photo-1595225476933-018acacc7d8d?auto=format&fit=crop&w=1200&q=80",
  },
};

// Fallback images for categories without specific product images
const fallbackCategoryImages = {
  Smartphones: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=1200",
  Laptops: "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1200",
  Headphones: "https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=1200",
  "Smart Watches": "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1200",
  "Gaming Accessories": "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1200",
  Tablets: "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1200",
  Cameras: "https://images.pexels.com/photos/606933/pexels-photo-606933.jpeg?auto=compress&cs=tinysrgb&w=1200",
  Speakers: "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=1200",
  Monitors: "https://images.pexels.com/photos/205335/pexels-photo-205335.jpeg?auto=compress&cs=tinysrgb&w=1200",
  "Keyboards & Mouse": "https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1200",
};

// Updated product definitions with better data
const productDefinitions = [
  {
    productName: "Apple iPhone 15 Pro",
    brand: "Apple",
    category: "Smartphones",
    price: 129999,
    originalPrice: 149999,
    discountPercentage: 13,
    stock: 140,
    rating: 4.9,
    numReviews: 1890,
    featured: true,
    shortDescription: "Flagship Apple smartphone with pro-level camera performance and premium titanium design.",
    fullDescription: "The Apple iPhone 15 Pro delivers pro-grade photography, a fast A17 Pro chip, excellent video capabilities, and a premium titanium frame for demanding users who want unrivaled performance and style.",
    specs: [
      ["Display", "6.1-inch Super Retina XDR OLED"],
      ["Processor", "Apple A17 Pro 6-core"],
      ["Storage", "256GB"],
      ["Camera", "48MP main, 12MP ultra-wide, 12MP telephoto"],
      ["Battery", "Up to 22 hours video playback"],
    ],
  },
  {
    productName: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "Smartphones",
    price: 119999,
    originalPrice: 134999,
    discountPercentage: 11,
    stock: 125,
    rating: 4.8,
    numReviews: 1525,
    featured: true,
    shortDescription: "High-end Android smartphone with advanced zoom camera and brilliant AMOLED display.",
    fullDescription: "Samsung Galaxy S24 Ultra brings flagship-level power, premium build quality, advanced AI processing, and a pro-grade camera array for photography enthusiasts.",
    specs: [
      ["Display", "6.8-inch Dynamic AMOLED 2X 120Hz"],
      ["Processor", "Snapdragon 8 Gen 3"],
      ["Storage", "512GB"],
      ["Camera", "200MP main, 50MP telephoto, 12MP ultra-wide"],
      ["Battery", "5000mAh with 45W fast charging"],
    ],
  },
  {
    productName: "Google Pixel 8 Pro",
    brand: "Google",
    category: "Smartphones",
    price: 99999,
    originalPrice: 114999,
    discountPercentage: 13,
    stock: 95,
    rating: 4.7,
    numReviews: 1190,
    featured: true,
    shortDescription: "Smartphone optimized for AI photography and stock Android experience.",
    fullDescription: "Google Pixel 8 Pro offers AI-powered imaging with advanced magic eraser, smooth display, and fast software updates for users who want pure Android flagship.",
    specs: [
      ["Display", "6.7-inch QHD+ OLED 120Hz"],
      ["Processor", "Google Tensor G3"],
      ["Storage", "256GB"],
      ["Camera", "50MP main, 48MP telephoto, 48MP ultra-wide"],
      ["Battery", "5050mAh with 37W fast charging"],
    ],
  },
  {
    productName: "Apple MacBook Pro 16",
    brand: "Apple",
    category: "Laptops",
    price: 254999,
    originalPrice: 289999,
    discountPercentage: 12,
    stock: 72,
    rating: 4.9,
    numReviews: 1140,
    featured: true,
    shortDescription: "High-performance laptop ideal for creative professionals and video editing.",
    fullDescription: "The MacBook Pro 16 delivers exceptional CPU and GPU power with the Apple M3 Pro, a premium Liquid Retina XDR display, and a long-lasting battery for creative professionals.",
    specs: [
      ["Processor", "Apple M3 Pro"],
      ["Display", "16.2-inch Liquid Retina XDR"],
      ["Memory", "32GB unified RAM"],
      ["Storage", "1TB SSD"],
      ["Battery", "Up to 22 hours"],
    ],
  },
  {
    productName: "Dell XPS 15",
    brand: "Dell",
    category: "Laptops",
    price: 184999,
    originalPrice: 209999,
    discountPercentage: 12,
    stock: 68,
    rating: 4.8,
    numReviews: 980,
    featured: true,
    shortDescription: "Slim premium laptop with vibrant OLED display and strong performance.",
    fullDescription: "Dell XPS 15 is designed for professionals with a compact form factor, stunning OLED screen, powerful Intel processor, and dedicated graphics.",
    specs: [
      ["Processor", "Intel Core i9-14900H"],
      ["Display", "15.6-inch OLED 3.5K 120Hz"],
      ["Memory", "32GB RAM"],
      ["Storage", "1TB SSD"],
      ["Graphics", "NVIDIA RTX 4060"],
    ],
  },
  {
    productName: "Sony WH-1000XM5",
    brand: "Sony",
    category: "Headphones",
    price: 24999,
    originalPrice: 27999,
    discountPercentage: 11,
    stock: 210,
    rating: 4.8,
    numReviews: 1780,
    featured: true,
    shortDescription: "Industry-leading noise cancelling wireless headphones with premium sound quality.",
    fullDescription: "Sony WH-1000XM5 offers exceptional active noise cancellation, premium sound quality, exceptional comfort, and advanced features for commuters and frequent travelers.",
    specs: [
      ["Type", "Over-ear wireless noise cancelling"],
      ["Battery", "Up to 30 hours"],
      ["Connectivity", "Bluetooth 5.4"],
      ["Noise Cancellation", "Adaptive Noise Control with AI"],
      ["Weight", "250g"],
    ],
  },
  {
    productName: "Bose QuietComfort Ultra",
    brand: "Bose",
    category: "Headphones",
    price: 27999,
    originalPrice: 30999,
    discountPercentage: 10,
    stock: 180,
    rating: 4.7,
    numReviews: 1285,
    featured: true,
    shortDescription: "Comfortable headphones with class-leading noise cancellation and balanced audio.",
    fullDescription: "Bose QuietComfort Ultra is built for long listening sessions, featuring effective noise cancellation, rich audio, and a lightweight design.",
    specs: [
      ["Type", "Over-ear wireless noise cancelling"],
      ["Battery", "Up to 30 hours"],
      ["Connectivity", "Bluetooth 5.3"],
      ["Noise Cancellation", "QuietComfort Noise Cancelling technology"],
      ["Weight", "250g"],
    ],
  },
  {
    productName: "Apple AirPods Max",
    brand: "Apple",
    category: "Headphones",
    price: 44999,
    originalPrice: 49999,
    discountPercentage: 10,
    stock: 132,
    rating: 4.7,
    numReviews: 980,
    featured: true,
    shortDescription: "Premium over-ear headphones with spatial audio and adaptive EQ technology.",
    fullDescription: "AirPods Max deliver immersive sound with spatial audio, superior noise cancellation, and seamless integration with Apple ecosystem.",
    specs: [
      ["Type", "Over-ear wireless premium headphones"],
      ["Battery", "Up to 20 hours"],
      ["Connectivity", "Apple H2 chip"],
      ["Audio", "Spatial audio with dynamic head tracking"],
      ["Weight", "384g"],
    ],
  },
  {
    productName: "Apple Watch Ultra 2",
    brand: "Apple",
    category: "Smart Watches",
    price: 89999,
    originalPrice: 99999,
    discountPercentage: 10,
    stock: 88,
    rating: 4.9,
    numReviews: 1310,
    featured: true,
    shortDescription: "Rugged premium smartwatch with advanced health tracking and GPS.",
    fullDescription: "Apple Watch Ultra 2 is designed for outdoor enthusiasts, delivering accurate fitness metrics, durable materials, and premium connectivity for serious athletes.",
    specs: [
      ["Display", "49mm Retina LTPO OLED"],
      ["Battery", "Up to 36 hours"],
      ["Connectivity", "LTE and Bluetooth"],
      ["Sensors", "ECG, Blood Oxygen, GPS+GLONASS"],
      ["Water Resistance", "100m"],
    ],
  },
  {
    productName: "Samsung Galaxy Watch 7",
    brand: "Samsung",
    category: "Smart Watches",
    price: 35999,
    originalPrice: 40999,
    discountPercentage: 12,
    stock: 118,
    rating: 4.7,
    numReviews: 950,
    featured: true,
    shortDescription: "Modern smartwatch with bright AMOLED screen and comprehensive health tools.",
    fullDescription: "Galaxy Watch 7 delivers sleek smartwatch styling, excellent battery life, and advanced health tracking for active users.",
    specs: [
      ["Display", "1.5-inch AMOLED"],
      ["Battery", "Up to 80 hours"],
      ["Connectivity", "Bluetooth, 4G LTE optional"],
      ["Sensors", "Heart rate, SpO2, sleep"],
      ["Water Resistance", "5ATM"],
    ],
  },
  {
    productName: "Sony Alpha a7 IV",
    brand: "Sony",
    category: "Cameras",
    price: 219999,
    originalPrice: 249999,
    discountPercentage: 12,
    stock: 54,
    rating: 4.9,
    numReviews: 670,
    featured: true,
    shortDescription: "Full-frame mirrorless camera built for hybrid photo and video shooters.",
    fullDescription: "Sony Alpha a7 IV delivers exceptional image quality, advanced autofocus, and professional video features in a compact mirrorless body.",
    specs: [
      ["Sensor", "33MP full-frame"],
      ["Video", "4K 60fps"],
      ["Autofocus", "Real-time Eye AF tracking"],
      ["ISO Range", "100-51200"],
      ["Stabilization", "5-axis in-body"],
    ],
  },
  {
    productName: "Canon EOS R6 Mark II",
    brand: "Canon",
    category: "Cameras",
    price: 239999,
    originalPrice: 269999,
    discountPercentage: 11,
    stock: 46,
    rating: 4.9,
    numReviews: 515,
    featured: true,
    shortDescription: "Professional full-frame mirrorless camera with fast autofocus and stabilization.",
    fullDescription: "Canon EOS R6 Mark II offers versatile stills and cinematic video capture, ideal for hybrid photographers and content creators.",
    specs: [
      ["Sensor", "24.2MP full-frame"],
      ["Video", "4K 60fps"],
      ["Autofocus", "Dual Pixel CMOS AF II"],
      ["ISO Range", "100-102400"],
      ["Stabilization", "5-axis in-body"],
    ],
  },
  {
    productName: "JBL Charge 5",
    brand: "JBL",
    category: "Speakers",
    price: 12999,
    originalPrice: 14999,
    discountPercentage: 13,
    stock: 210,
    rating: 4.6,
    numReviews: 1180,
    featured: true,
    shortDescription: "Portable Bluetooth speaker with punchy sound and long battery life.",
    fullDescription: "JBL Charge 5 is perfect for outdoor listening, offering powerful bass, durable construction, and a 20-hour battery for extended adventures.",
    specs: [
      ["Connectivity", "Bluetooth 5.1"],
      ["Battery", "Up to 20 hours"],
      ["Waterproof Rating", "IP67"],
      ["Power Output", "40W"],
      ["Features", "PartyBoost mode"],
    ],
  },
  {
    productName: "Bose SoundLink Revolve+",
    brand: "Bose",
    category: "Speakers",
    price: 22999,
    originalPrice: 25999,
    discountPercentage: 12,
    stock: 145,
    rating: 4.7,
    numReviews: 980,
    featured: true,
    shortDescription: "360-degree portable speaker with balanced audio and premium build.",
    fullDescription: "SoundLink Revolve+ delivers rich, immersive 360-degree sound in a stylish portable speaker with excellent connectivity.",
    specs: [
      ["Connectivity", "Bluetooth 5.0"],
      ["Battery", "Up to 16 hours"],
      ["Water Resistance", "IPX4"],
      ["Audio", "360-degree sound"],
      ["Features", "Speakerphone"],
    ],
  },
  {
    productName: "Apple iPad Pro 13",
    brand: "Apple",
    category: "Tablets",
    price: 114999,
    originalPrice: 129999,
    discountPercentage: 11,
    stock: 74,
    rating: 4.9,
    numReviews: 760,
    featured: true,
    shortDescription: "Powerful tablet for creative professionals with stunning Liquid Retina XDR display.",
    fullDescription: "Apple iPad Pro 13 delivers top-tier performance for productivity, sketching, and media creation in a sleek tablet format.",
    specs: [
      ["Display", "13-inch Liquid Retina XDR"],
      ["Processor", "Apple M4"],
      ["Storage", "512GB"],
      ["Camera", "12MP front, 12MP rear"],
      ["Connectivity", "Wi-Fi 6E + 5G"],
    ],
  },
  {
    productName: "Samsung Galaxy Tab S9+",
    brand: "Samsung",
    category: "Tablets",
    price: 77999,
    originalPrice: 85999,
    discountPercentage: 9,
    stock: 98,
    rating: 4.8,
    numReviews: 590,
    featured: true,
    shortDescription: "Premium Android tablet with productivity-focused features and S Pen support.",
    fullDescription: "Galaxy Tab S9+ is ideal for designers and multitaskers, offering a bright AMOLED screen and responsive stylus experience.",
    specs: [
      ["Display", "12.4-inch Super AMOLED"],
      ["Processor", "Snapdragon 8 Gen 2"],
      ["Storage", "256GB"],
      ["Camera", "13MP rear, 12MP front"],
      ["Battery", "10090mAh"],
    ],
  },
  {
    productName: "Dell UltraSharp U2724D",
    brand: "Dell",
    category: "Monitors",
    price: 41999,
    originalPrice: 47999,
    discountPercentage: 12,
    stock: 98,
    rating: 4.8,
    numReviews: 450,
    featured: true,
    shortDescription: "Professional 27-inch monitor with sharp QHD resolution and accurate color.",
    fullDescription: "Dell UltraSharp U2724D delivers crisp detail, wide color coverage, and reliable ergonomics for creative work and office productivity.",
    specs: [
      ["Size", "27-inch"],
      ["Resolution", "QHD 2560x1440"],
      ["Panel Type", "IPS"],
      ["Refresh Rate", "60Hz"],
      ["Connectivity", "HDMI, DisplayPort, USB-C"],
    ],
  },
  {
    productName: "Samsung Odyssey G7",
    brand: "Samsung",
    category: "Monitors",
    price: 64999,
    originalPrice: 72999,
    discountPercentage: 11,
    stock: 82,
    rating: 4.8,
    numReviews: 520,
    featured: true,
    shortDescription: "Curved gaming monitor with fast refresh rate and deep contrast.",
    fullDescription: "Samsung Odyssey G7 delivers immersive gameplay with QHD resolution, 240Hz speed, and a curved VA panel for gaming.",
    specs: [
      ["Size", "27-inch"],
      ["Resolution", "QHD 2560x1440"],
      ["Panel Type", "VA"],
      ["Refresh Rate", "240Hz"],
      ["Response Time", "1ms"],
    ],
  },
  {
    productName: "Logitech MX Keys",
    brand: "Logitech",
    category: "Keyboards & Mouse",
    price: 8999,
    originalPrice: 10999,
    discountPercentage: 18,
    stock: 220,
    rating: 4.8,
    numReviews: 950,
    featured: true,
    shortDescription: "Premium wireless keyboard designed for productivity with responsive keys.",
    fullDescription: "Logitech MX Keys is built for professionals, offering quiet typing, smart illumination, and multi-device support.",
    specs: [
      ["Connectivity", "Bluetooth / 2.4GHz receiver"],
      ["Battery", "Up to 10 days"],
      ["Layout", "Full-size"],
      ["Features", "Smart backlighting"],
      ["Compatibility", "Windows, Mac, Linux"],
    ],
  },
  {
    productName: "Logitech MX Master 3S",
    brand: "Logitech",
    category: "Keyboards & Mouse",
    price: 9999,
    originalPrice: 11999,
    discountPercentage: 17,
    stock: 210,
    rating: 4.9,
    numReviews: 1125,
    featured: true,
    shortDescription: "Premium ergonomic mouse with advanced tracking and customizable controls.",
    fullDescription: "MX Master 3S delivers remarkable precision, ergonomic comfort, and programmable buttons for power users.",
    specs: [
      ["Sensor", "Darkfield 8K"],
      ["Connectivity", "Bluetooth / 2.4GHz"],
      ["Battery", "Up to 70 hours"],
      ["Programmable Buttons", "7"],
      ["Features", "MagSpeed scroll wheel"],
    ],
  },
  {
    productName: "Razer Huntsman V2 Analog Keyboard",
    brand: "Razer",
    category: "Gaming Accessories",
    price: 19999,
    originalPrice: 22999,
    discountPercentage: 13,
    stock: 110,
    rating: 4.8,
    numReviews: 875,
    featured: true,
    shortDescription: "Premium gaming keyboard with analog switches and customizable RGB lighting.",
    fullDescription: "Razer Huntsman V2 Analog offers precise actuation, responsive keys, and extensive customization for competitive gamers.",
    specs: [
      ["Switches", "Analog optical switches"],
      ["Keycaps", "Doubleshot ABS"],
      ["Backlight", "Chroma RGB per-key"],
      ["Connectivity", "USB-C"],
      ["Macros", "Fully programmable"],
    ],
  },
];

// Helper function to get product images
function getProductImages(productName) {
  if (productImages[productName]) {
    return [
      productImages[productName].primary,
      productImages[productName].secondary,
      productImages[productName].tertiary,
    ];
  }
  return [fallbackCategoryImages["Smartphones"], fallbackCategoryImages["Smartphones"], fallbackCategoryImages["Smartphones"]];
}

const sampleProducts = productDefinitions.map((product) => {
  const images = getProductImages(product.productName);
  return {
    productName: product.productName,
    shortDescription: product.shortDescription,
    fullDescription: product.fullDescription,
    productDesc: product.shortDescription,
    price: product.price,
    productPrice: product.price,
    originalPrice: product.originalPrice,
    discountPercentage: product.discountPercentage,
    stock: product.stock,
    thumbnail: images[0],
    images: images,
    productImg: [
      {
        url: images[0],
        public_id: `product_${product.productName.replace(/\s+/g, "_").toLowerCase()}`,
      },
    ],
    rating: product.rating,
    numReviews: product.numReviews,
    specifications: product.specs.map(([label, value]) => ({ label, value })),
    featured: product.featured,
    category: product.category,
    brand: product.brand,
  };
});

const seedDatabase = async () => {
  try {
    await connectDB();

    // Check for existing products
    const existingCount = await Product.countDocuments();
    
    if (existingCount > 0) {
      console.log(`Found ${existingCount} existing products. Skipping seed to prevent duplicates.`);
      console.log("To refresh products, run: npm run cleanup:products && npm run seed:products:v2");
      process.exit(0);
    }

    await Product.insertMany(sampleProducts);
    console.log(`✅ Successfully inserted ${sampleProducts.length} products with verified images into MongoDB.`);
    process.exit(0);
  } catch (error) {
    console.error("❌ Failed to seed products:", error.message);
    process.exit(1);
  }
};

await seedDatabase();
